### PR TITLE
Dw/regex

### PR DESCRIPTION
**Pull request by D-Town44**
## 📖 Description and reason

Add Regex functionality to `excluded_paths` option

#### Tasks

- [x] Test Run
- [x] Task 2

#### Additional notes

Also updated the version/readme/tests

## 🎉 Result

image

## 🦀 Dispatch

`#dispatch/elixir`

### CODE REVIEW

**Comment by D-Town44** [comment]
Added Regex Functionality. Updated Version/Readme/Tests

**Comment by remi** [comment]
Hi Daniel,

Could you exclude the version/changelog update from your PR. We like to keep actual feature code separate from version changes.

Thank you!

**Comment by D-Town44** [comment]
No problem! Removed 👍

**Comment by remi** [comment]
Thank you @D-Town44! I just released v2.0.1 with your feature 🎉

**Pull request merged**
