### PR TITLE
refactor: validate phoenix paths

### PR DESCRIPTION
**Pull request by duzzifelipe**
I saw on the readme that there are some plans to support "flavors" of validations.

Currently I see some projects that I'm involved in just ignoring the `*_web` (and its test) folder to avoid this library's errors.

My first commit on this branch (https://github.com/mirego/credo_naming/commit/a00afcbc3b8c348c15932b37ca37c3351ed46f7b) just adds something like this "flavor" idea.

But after some tries, I saw that the current code is making some strange validations:
 - on the suggestion list there are some dot-separated paths, such as `lib/my_app_web.service.user_controller.ex` and `lib/my_app_web/service.user_controller.ex` that makes no sense for me;
 - also there is an option repeating the file name like `lib/my_app_web/service/user_controller/user_controller.ex for a module named `MyAppWeb.Service.UserController`:
  - this problem also gives us some false negatives, like when you have a module named `Service.MyContext` that is wrongly placed  in `/service/my_context/my_context` and the current behavior says it is ok.

Then I came up with a little refactor on this path validation also mixing up with the newly "phoenix flavor" by default (so there is no option such as in first commit to enable phoenix validation).

### CODE REVIEW

**Review by george124816 — APPROVED** [review]

**Review by aschiavon91 — APPROVED** [review]

**Comment by remi** [comment]
@duzzifelipe Hi! Terribly for the long delay on this 🤦‍♂️ I think what this PR needs is just some tests to make sure these newly supported cases are documented. What do you think?

**Comment by duzzifelipe** [comment]
@remi I entirely forgot about tests. Now I wrote them and also split the phoenix-specific validation into a module. This way, users can choose if they will check for phoenix naming consistency.

**Comment by prem-prakash** [comment]
@duzzifelipe any chance to get this moving?

**Comment by duzzifelipe** [comment]
@prem-prakash its currently just waiting for review. 

I think there is a decision from @remi with 2 breaking changes I've inserted:

- no support for filenames with dots, such as `my.controller.ex` (the only format accepted now is `my_controller.ex`);
- no support for "index" files. Before you were allowed to have `my_app/context/context.ex` with a module named `MyApp.Context` (the file and the previous folder with same name). With this PR, having a file in `my_app/context/context.ex` would require a module named `MyApp.Context.Context`

**Comment by prem-prakash** [comment]
Ok, about the breaking changes:
 - no support for filenames with dots -> acceptable
 - no support for "index" files -> very questionable, because contexts are a pattern in the elixir/phoenix community, and having a `MyApp.Context.Context` is not an acceptable requirement (IMHO). Any chance of accepting of adapting your PR to accept a `my_app/context/context.ex` to be named `MyApp.Context`?

**Comment by duzzifelipe** [comment]
@prem-prakash I changed the PR to put this "context index" pattern back. I removed it because I was trying to be as much simpler as possible by just converting module names into paths directly.

Take a look at my last commit. To be honest, I didn't like it too much, but I don't have any other idea on how to do this since I must duplicate the list of valid paths

**Comment by prem-prakash** [comment]
Hey @duzzifelipe, it looks good enough to me.
@miregoit can take a look, please?

**Comment by remi** [comment]
:tada: This is great! I’ll wait for the CI build and then merge it.

I’ll then document the new `plugins` option in `README.md`, changes in `CHANGELOG.md` and cut a new release. Probably 2.0.0 because of the “dot-in-filenames” breaking change. What do you think?

**Comment by remi** [comment]
@duzzifelipe Yep it should. Please rebase your branch against `master`! 🙏

**Comment by duzzifelipe** [comment]
@remi done

**Comment by remi** [comment]
All green, let’s go! 🚀

**Comment by remi** [comment]
@duzzifelipe @prem-prakash `credo_naming` 2.0.0 has been published! 🎉

**Comment by remi** [comment]
@duzzifelipe I also added you to the `README.md`’s contributors list 🙌

**Pull request merged**
